### PR TITLE
fixed NaN error and formatted code

### LINKED ISSUE #327: Signal Projects dashboard modal displays "NaN" under "Updated" field
@tcwcodes commented on [Thu Oct 10 2019](https://github.com/cityofaustin/atd-vz-data/issues/275)

https://transportation.austintexas.io/signal-projects/

---

@mateoclarke commented on [Sun Oct 13 2019](https://github.com/cityofaustin/atd-vz-data/issues/275#issuecomment-541503195)

@tcwcodes I think you added this issue to the wrong repo. Can you move it to https://github.com/cityofaustin/transportation.austintexas.io

---

@tcwcodes commented on [Mon Oct 14 2019](https://github.com/cityofaustin/atd-vz-data/issues/275#issuecomment-541736519)

> @tcwcodes I think you added this issue to the wrong repo. Can you move it to https://github.com/cityofaustin/transportation.austintexas.io

You're right, I must have left it under the default branch by accident. Moving it now, thanks for the heads up!

### PR DESCRIPTION
**Pull request by tcwcodes**
Fixes #327 

If a record doesn't have an updated date, the updated field is not displayed at all (rather than showing "Updated: NaN").

Also formatted the code for this file.

I added a comment in the code in GitHub to show the section that I actually changed. Sorry if it's hard to read due to all the formatting changes! I basically just added a logical statement to only show the data if it exists within a record.

Screen Shot 2020-01-22 at 11 07 38 AM

### CODE REVIEW

File: components/js/signal-projects.js [hunk 1]
```diff
@@ -1,629 +1,601 @@
...
 
-        var location_name = data[i].location_name;
+    var marker_style = default_style[status];
 
-        var lat = data[i].location_latitude;
-        
-        var lon = data[i].location_longitude;
+    var location_name = data[i].location_name;
 
-        var updated = formats.formatDate( new Date(data[i].construction_note_date) )
```
Comment (tcwcodes) [inline components/js/signal-projects.js]: Sorry if this is hard to read due to all the reformatting, but this section contains the code I actually edited!

Comment (mateoclarke) [reply components/js/signal-projects.js]: nice, thanks for highlighting the right section.
